const fs = require("fs");
const path = require("path");

// Resolve source modules and generated artifacts relative to the project root.
const ROOT = __dirname;
const CORE_MODULES_DIR = path.join(ROOT, "core_modules");
const OUTPUT_PATH = path.join(ROOT, "bilibili_cleaner.js");
const GENERATED_BANNER = [
  "/*",
  " * Generated by build_bilibili_cleaner.js from core_modules.",
  " * Edit module sources and rebuild; do not edit this file directly.",
  " */",
  "",
].join("\n");

// Concatenate modules in runtime dependency order; keep the TECH.md ownership table in sync.
const CORE_MODULE_FILES = [
  "Common/config.js",
  "Common/runtime-protobuf.js",
  "Common/filter-rules.js",
  "Common/tag-cache.js",
  "Common/protobuf-tools.js",
  "Common/video-search.js",
  "iOS/video.js",
  "iPadOS/video.js",
  "Common/reply.js",
  "Common/json-page-handlers.js",
  "iOS/home-tabs.js",
  "Common/mine.js",
  "iOS/mine.js",
  "iPadOS/mine.js",
  "iPadOS/ads.js",
  "Common/live-and-modes.js",
  "Common/dynamic.js",
  "Common/home-feed.js",
  "Common/entry.js",
];

// Build one Loon-compatible script without adding a module loader or extra scope.
function buildCleanerSource() {
  return GENERATED_BANNER + CORE_MODULE_FILES
    .map((file) => fs.readFileSync(path.join(CORE_MODULES_DIR, file), "utf8"))
    .join("");
}

// Verify that the committed bundle exactly matches the current module sources.
function checkCleanerBuild() {
  const generated = buildCleanerSource();
  const current = fs.readFileSync(OUTPUT_PATH, "utf8");
  if (current !== generated) {
    throw new Error(
      "bilibili_cleaner.js 与 core_modules 模块不同步，请运行 node build_bilibili_cleaner.js"
    );
  }
  return true;
}

// Write the current module sources to the generated root-level bundle.
function writeCleanerBuild() {
  const generated = buildCleanerSource();
  fs.writeFileSync(OUTPUT_PATH, generated);
  return generated;
}

if (require.main === module) {
  try {
    if (process.argv.includes("--check")) {
      checkCleanerBuild();
      console.log("bilibili_cleaner.js is up to date");
    } else {
      writeCleanerBuild();
      console.log(`built ${path.relative(ROOT, OUTPUT_PATH)}`);
    }
  } catch (error) {
    console.error(error.message || error);
    process.exitCode = 1;
  }
}

module.exports = {
  CORE_MODULE_FILES,
  GENERATED_BANNER,
  OUTPUT_PATH,
  CORE_MODULES_DIR,
  buildCleanerSource,
  checkCleanerBuild,
  writeCleanerBuild,
};
